In [39]:
import pandas as pd
import numpy as np

In [40]:
atlanta_df = pd.read_csv("Resources/atlanta_raw.csv")
atlanta_df.head()

,Fiscal Year,Fiscal_Period,Check Date,Fund_Type,Fund,Department,Division,Account,Expense_Category,Project,Invoice Description,Amount,Vendor Name,Vendor Id,Payment Id,Payment Method,Payment_Status,Payment_Check_Num
0,2017,7,2017-01-31T00:00:00.000,ENTERPRISE FUNDS,2015A WATER COMMERICAL PAPER PROGRAM,DEPARTMENT OF WATERSHED MANAGEMENT,DWM WATER LINEAR MAINTENANCE/REPAIR,FACILITIES OTHER THAN BLDGS/INFRASTRUCTURE - CIP,CAPITAL OUTLAYS,RAW WATER DELIVERY PROGRAM,NaN,21377988.87,"PC/RUSSELL, A JOINT VENTURE",17016120,622923,EFT,NaN,3086468
1,2017,8,2017-02-10T00:00:00.000,ENTERPRISE FUNDS,DOA SERIES 2015 COMMERCIAL PAPER PROGRAM,DEPARTMENT OF AVIATION,DOA AVIATION CAPITAL PLANNING & DEVELOPMENT,FACILITIES OTHER THAN BLDGS/INFRASTRUCTURE - CIP,CAPITAL OUTLAYS,TERMINAL & ATRIUM PROJECTS,NaN,18811754.57,DELTA AIR LINES,1924,624898,EFT,NaN,3087035
2,2017,10,2017-04-03T00:00:00.000,ENTERPRISE FUNDS,2015A WATER COMMERICAL PAPER PROGRAM,DEPARTMENT OF WATERSHED MANAGEMENT,DWM WATER LINEAR MAINTENANCE/REPAIR,FACILITIES OTHER THAN BLDGS/INFRASTRUCTURE - CIP,CAPITAL OUTLAYS,RAW WATER DELIVERY PROGRAM,NaN,16895495.40,"PC/RUSSELL, A JOINT VENTURE",17016120,634974,EFT,NaN,3090080
3,2017,6,2016-12-13T00:00:00.000,ENTERPRISE FUNDS,2015A WATER COMMERICAL PAPER PROGRAM,DEPARTMENT OF WATERSHED MANAGEMENT,DWM WATER LINEAR MAINTENANCE/REPAIR,FACILITIES OTHER THAN BLDGS/INFRASTRUCTURE - CIP,CAPITAL OUTLAYS,RAW WATER DELIVERY PROGRAM,NaN,15847195.84,"PC/RUSSELL, A JOINT VENTURE",17016120,613901,EFT,NaN,3083758
4,2017,8,2017-02-10T00:00:00.000,ENTERPRISE FUNDS,AIRPORT RENEWAL AND EXTENSION FUND,DEPARTMENT OF AVIATION,DOA AVIATION CAPITAL PLANNING & DEVELOPMENT,FACILITIES OTHER THAN BLDGS/INFRASTRUCTURE - CIP,CAPITAL OUTLAYS,OTHER FACILITY PROJECTS,NaN,12553535.53,"DUNN AVIATION GROUP, A JOINT VENTURE",16488117,625069,CHECK,NaN,2344308

In [41]:
atlanta_df2 = atlanta_df.loc[atlanta_df["Fiscal Year"]==2018]
atlanta_df2.head()

,Fiscal Year,Fiscal_Period,Check Date,Fund_Type,Fund,Department,Division,Account,Expense_Category,Project,Invoice Description,Amount,Vendor Name,Vendor Id,Payment Id,Payment Method,Payment_Status,Payment_Check_Num
54340,2018,12,2018-06-29T00:00:00.000,GENERAL FUNDS,GENERAL FUND,DEPARTMENT OF FIRE SERVICES,AFR FIRE FIGHTING,TRAINING TRAVEL / PER DIEM,PURCHASED / CONTRACTED SERVICES,DEFAULT,Closeout for Prisonser booked under incorrect ...,429.30,"Weaver, Abe",18869896,714934,CREDIT CARD,NaN,8600860
54341,2018,12,2018-06-29T00:00:00.000,GENERAL FUNDS,GENERAL FUND,DEPARTMENT OF POLICE SERVICES,APD CODE ENFORCEMENT,TRAINING TRAVEL / PER DIEM,PURCHASED / CONTRACTED SERVICES,DEFAULT,GACE Conference IEX553578,475.65,"Tucker, Stanley J",10201,714933,CREDIT CARD,NaN,8600859
54342,2018,12,2018-06-29T00:00:00.000,SPECIAL REVENUE FUNDS,EMERGENCY TELEPHONE SYSTEM,DEPARTMENT OF POLICE SERVICES,APD E-911,TRAINING TRAVEL / PER DIEM,PURCHASED / CONTRACTED SERVICES,DEFAULT,GECC 2018 Conference IEX553330,536.00,"Smith, Felicia Nicole",18853901,714932,CREDIT CARD,NaN,8600858
54343,2018,12,2018-06-29T00:00:00.000,GENERAL FUNDS,GENERAL FUND,DEPARTMENT OF CORRECTIONS,COR PRETRIAL DETENTION CENTER,TRAINING TRAVEL / PER DIEM,PURCHASED / CONTRACTED SERVICES,DEFAULT,18-May-2018 - 2018 CAMA Professional Developme...,687.48,"Pritchett, Amanda",18760884,714931,CREDIT CARD,NaN,8600857
54344,2018,12,2018-06-29T00:00:00.000,GENERAL FUNDS,GENERAL FUND,DEPARTMENT OF POLICE SERVICES,APD COMMUNITY ORIENTED POLICING SECTION,TRAINING TRAVEL / PER DIEM,PURCHASED / CONTRACTED SERVICES,DEFAULT,Booked Prisoner Airfare Brejon Nabors IEX554639,250.20,"Mathis, Tammy L",18828883,714930,CREDIT CARD,NaN,8600856

In [42]:
atlanta_df2["Department"].unique()

array(['DEPARTMENT OF FIRE SERVICES', 'DEPARTMENT OF POLICE SERVICES',
       'DEPARTMENT OF CORRECTIONS',
       'DEPT OF PLANNING & COMMUNITY DEVELOPMENT',
       'DEPARTMENT OF PUBLIC WORKS', 'EXECUTIVE OFFICES',
       'DEPT OF PARKS, RECREATION & CULTURAL AFF',
       'DEPARTMENT OF HUMAN RESOURCES', 'DEPARTMENT OF AVIATION',
       'DEPARTMENT OF WATERSHED MANAGEMENT', 'DEPARTMENT OF LAW',
       'DEPARTMENT OF PUBLIC DEFENDER', 'DEPARTMENT OF PROCUREMENT',
       'DEPARTMENT OF FINANCE', 'DEPARTMENT OF AUDIT', 'CITY COUNCIL',
       'JUDICIAL AGENCIES', 'ATLANTA CITIZENS REVIEW BOARD',
       'DEPARTMENT OF INFORMATION TECHNOLOGY', 'DEPARTMENT OF ETHICS',
       'NON-DEPARTMENTAL', 'DEPARTMENT OF THE SOLICITOR'], dtype=object)

In [53]:
atlanta_df3 = atlanta_df2.groupby(["Department"]).sum().rename_axis("Departments")

atlanta_df3.head()

,Fiscal Year,Fiscal_Period,Amount,Vendor Id,Payment Id,Payment_Status,Payment_Check_Num
Departments,,,,,,,
ATLANTA CITIZENS REVIEW BOARD,659886,1996,1.064085e+05,3903582554,223233030,0.0,1022641243
CITY COUNCIL,2655688,8786,1.873115e+06,8875008818,901947384,0.0,4415754328
DEPARTMENT OF AUDIT,912136,2850,2.026825e+06,3496842138,308773928,0.0,1538609983
DEPARTMENT OF AVIATION,11052586,35231,4.653970e+08,34191613705,3747044082,0.0,18867237423
DEPARTMENT OF CORRECTIONS,2560842,8229,5.944465e+06,5428635025,868460452,0.0,4343470700

In [54]:
atlanta_df4 = atlanta_df3[[ "Amount"]]
atlanta_df4

                                                Amount
Departments
ATLANTA CITIZENS REVIEW BOARD             1.064085e+05
CITY COUNCIL                              1.873115e+06
DEPARTMENT OF AUDIT                       2.026825e+06
DEPARTMENT OF AVIATION                    4.653970e+08
DEPARTMENT OF CORRECTIONS                 5.944465e+06
DEPARTMENT OF ETHICS                      2.920272e+05
DEPARTMENT OF FINANCE                     1.300237e+07
DEPARTMENT OF FIRE SERVICES               5.733074e+06
DEPARTMENT OF HUMAN RESOURCES             2.355699e+06
DEPARTMENT OF INFORMATION TECHNOLOGY      2.325765e+07
DEPARTMENT OF LAW                         7.874519e+06
DEPARTMENT OF POLICE SERVICES             2.479392e+07
DEPARTMENT OF PROCUREMENT                 2.648139e+05
DEPARTMENT OF PUBLIC DEFENDER             2.039389e+05
DEPARTMENT OF PUBLIC WORKS                1.310799e+08
DEPARTMENT OF THE SOLICITOR               1.922078e+05
DEPARTMENT OF WATERSHED MANAGEMENT        2.839051e+08
DEPT OF PARKS, RECREATION & CULTURAL AFF  2.876676e+07
DEPT OF PLANNING & COMMUNITY DEVELOPMENT  1.531775e+07
EXECUTIVE OFFICES                         6.785693e+07
JUDICIAL AGENCIES                         2.562016e+06
NON-DEPARTMENTAL                          3.330483e+07

In [55]:
print(len(atlanta_df4))
classification = [4, 4, 4, 7, 6, 4, 3, 6, 3, 3, 4, 6, 4, 4,  7, 4, 7, 2, 5, 4, 4, 8]
len(classification)

22

22

In [56]:
department_name = []

for x in classification:
    if x == 1:
        department_name.append("Community Health")
    if x == 2:
        department_name.append("Culture & Recreation")
    if x == 3:
        department_name.append("General  Administration & Finance")
    if x==4:
        department_name.append("General City Responsibilities")
    if x ==5:
        department_name.append("Human Welfare & Neighborhood Development")
    if x==6:
        department_name.append("Public Protection")
    if x ==7:
        department_name.append("Public Works/Transportation & Commerce")
    if x ==8:
        department_name.append("Other")

In [57]:
atlanta_df4["Department"] = department_name

/Users/Axewave/opt/anaconda3/envs/PythonData2/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [58]:
atlanta_df5 = atlanta_df4.groupby(["Department"]).sum()

In [59]:
atlanta_df5

                                                Amount
Department
Culture & Recreation                      2.876676e+07
General  Administration & Finance         3.861572e+07
General City Responsibilities             8.325281e+07
Human Welfare & Neighborhood Development  1.531775e+07
Other                                     3.330483e+07
Public Protection                         3.647146e+07
Public Works/Transportation & Commerce    8.803819e+08

In [60]:
atlanta_df5.to_csv("Transformed/Atlanta.csv")